# Generated by Django 5.0.4 on 2024-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course', models.CharField(choices=[('BS-IT', 'Information Technology'), ('BS-CS', 'Computer Science'), ('BS-DS', 'Data Science'), ('BS-IS', 'Information Systems')], max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course', models.CharField(choices=[('BS-IT', 'Information Technology'), ('BS-CS', 'Computer Science'), ('BS-DS', 'Data Science'), ('BS-IS', 'Information Systems')], max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
    ]
