# Generated by Django 5.0.4 on 2024-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='course',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='add',
            name='gender',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
